### ISSUE TITLE
사용자 사전 관련 문의

### ISSUE THREAD

**Issue by ByungjunKim** [baikalai/baikalnlpy#1]
안녕하세요 이번 1.5 업데이트되서 쭉 사용중인데, 정말 좋은 형태소 분석기입니다.
제가 지난달에 경황이 없어서 deeqnlpy를 잘 살펴볼 시간이 없었는데, 바로 수업에 적용하지 못해 아쉬울 정도입니다.
사용자 사전 관련 질문이 있습니다.
아래 사용자 사전 예시 코드에서. cp_caret_set은 이해 했습니다. 띄어쓰기가 들어간 복합명사(compound noun)를 인식시킬때 쓰는 것이고요.
np_set이랑 cp_set의 차이를 잘 모르겠습니다. 

좋은 패키지 공개해주셔서 감사합니다.
```
cust_dic.copy_np_set({'내고유명사', '우리집고유명사'})
cust_dic.copy_cp_set({'코로나19'})
cust_dic.copy_cp_caret_set({'코로나^백신', '"독감^백신'})
```

**Comment by gih2yun** [comment]
@ByungjunKim 님, 반갑습니다.

`np_set`은 고유명사로 사용할 단어들의 집합을 말합니다.
`cp_set`은 특정 도메인에서 복합명사 굳어진 형태여서 일반명사로 인식하게 할 단어들의 집합입니다.

`np_set`은 NNP가 되고, `cp_set`은 NNG가 됩니다.

참고로 cp_caret_set의 경우에는 다시 각 조합의 일부분들이 NNG가 될수도 있고, NNP가 될 수도 있습니다.

**Comment by ByungjunKim** [comment]
헉 대표님이 직접 달아주셨군요. 친절한 설명 감사합니다.
사용자 사전이 굉장히 섬세하네요. 활용해보겠습니다.
